# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true  # Hủy job cũ nếu có job mới trigger

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for 1 minutes
        run: sleep 60  # Đợi 1 phút để chắc chắn không có commit mới

      - name: Fetch latest commit
        run: git fetch origin main

      - name: Check if latest commit has changed
        id: check_latest
        run: |
          LATEST_COMMIT=$(git rev-parse origin/main)
          echo "Latest commit: $LATEST_COMMIT"
          echo "LATEST_COMMIT=$LATEST_COMMIT" >> $GITHUB_ENV

      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.LATEST_COMMIT }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
